FROM node:20-alpine AS build

WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

COPY package.json pnpm-lock.yaml ./
COPY vendor/providers ./vendor/providers
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

ARG PWA_ENABLED="true"
ARG APP_DOMAIN="http://localhost:8080"
ARG BASE_URL="/"
ARG OPENSEARCH_ENABLED="false"
ARG TMDB_READ_API_KEY
ARG CORS_PROXY_URL
ARG M3U8_PROXY_URL
ARG DMCA_EMAIL
ARG NORMAL_ROUTER="true"
ARG BACKEND_URL
ARG HAS_ONBOARDING="true"
ARG HIDE_PROXY_ONBOARDING="false"
ARG ONBOARDING_CHROME_EXTENSION_INSTALL_LINK
ARG ONBOARDING_FIREFOX_EXTENSION_INSTALL_LINK
ARG ONBOARDING_PROXY_INSTALL_LINK
ARG DISALLOWED_IDS
ARG CDN_REPLACEMENTS
ARG ALLOW_AUTOPLAY="false"
ARG ALLOW_FEBBOX_KEY="false"
ARG ALLOW_DEBRID_KEY="false"

ENV VITE_PWA_ENABLED=${PWA_ENABLED}
ENV VITE_APP_DOMAIN=${APP_DOMAIN}
ENV VITE_BASE_URL=${BASE_URL}
ENV VITE_OPENSEARCH_ENABLED=${OPENSEARCH_ENABLED}
ENV VITE_TMDB_READ_API_KEY=${TMDB_READ_API_KEY}
ENV VITE_CORS_PROXY_URL=${CORS_PROXY_URL}
ENV VITE_M3U8_PROXY_URL=${M3U8_PROXY_URL}
ENV VITE_DMCA_EMAIL=${DMCA_EMAIL}
ENV VITE_NORMAL_ROUTER=${NORMAL_ROUTER}
ENV VITE_BACKEND_URL=${BACKEND_URL}
ENV VITE_HAS_ONBOARDING=${HAS_ONBOARDING}
ENV VITE_HIDE_PROXY_ONBOARDING=${HIDE_PROXY_ONBOARDING}
ENV VITE_ONBOARDING_CHROME_EXTENSION_INSTALL_LINK=${ONBOARDING_CHROME_EXTENSION_INSTALL_LINK}
ENV VITE_ONBOARDING_FIREFOX_EXTENSION_INSTALL_LINK=${ONBOARDING_FIREFOX_EXTENSION_INSTALL_LINK}
ENV VITE_ONBOARDING_PROXY_INSTALL_LINK=${ONBOARDING_PROXY_INSTALL_LINK}
ENV VITE_DISALLOWED_IDS=${DISALLOWED_IDS}
ENV VITE_CDN_REPLACEMENTS=${CDN_REPLACEMENTS}
ENV VITE_ALLOW_AUTOPLAY=${ALLOW_AUTOPLAY}
ENV VITE_ALLOW_FEBBOX_KEY=${ALLOW_FEBBOX_KEY}
ENV VITE_ALLOW_DEBRID_KEY=${ALLOW_DEBRID_KEY}

COPY . ./
RUN pnpm build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1/ping.txt >/dev/null || exit 1

CMD ["nginx", "-g", "daemon off;"]
